class Mensajes:
    esp = {"mat": "Materia", "idi": "1 para Español, 2 para Ingles", "id": "Id", "idePro": "Identificación de profesor",
           "ideEstu": "Identificación del estudiante: ", "ideMate": "Identificación de la materia: ", "menuMatt": "1. Buscar materia\n2. Generar reporte\n3. Salir\n",
           "numGrp": "Número del grupo: ", "ideNot": "Identificación de la nota: ", "reporte": "Reporte generado", "reportErr": "Error inesperado: Permiso denegado.",
           "nom": "Nombre", "cre": "Creditos", "gru": "Grupo", "reg": "Registrado", "mod": "Modificado",
           "err": "Error", "eli": "Eliminado", "num": "Numero", "pro": "Profesor",
           "usu": "Usuario", "ide": "Identificación", "cor": "Correo", "con": "Contraseña",
           "not": "Nota", "por": "Porcentaje", "val": "Valor", "ing Usu": "Ingrese su identificación o correo electronico: ",
           "opnot": "1. Registrar\n2. Modificar\n3.Borrar\n4. Buscar\n5. Salir\n", "noenc": "No encontrado",
           "ing Con": "Ingrese su contraseña: ", "bie": "Bienvenido", "o": "o", "enc": "Encontrad@",
           "opc1": "1. Iniciar sesión\n2. Cerrar aplicación\n3. Recuperar contraseña\n",
           "opcAdmin": "1. Estudiante\n2. Profesor\n3. Administrador\n4. Materia\n5. Grupo\n6. Cerrar sesion\n",
           "opcProf": "1. Nota\n2. Grupo\n3. Materia\n4. Cerrar sesion\n",
           "CASE": "1. Registrar\n2. Consultar\n3. Modificar\n4. Eliminar\n5. Listar \n6. Volver", "busgrp": "1. Buscar grupo\n2. Salir\n",
           "CASEGru": "1. Registrar\n2. Consultar\n3. Modificar\n4. Eliminar\n5. Listar todo\n6. Listar por materia \n7. Volver",
           "codi": "Codigo: ", "recu": "Recuperación de contraseña", "nuecon": "Nueva Contraseña: ", "menuEstu": "1. Nota\n2. Matrícula\n3. Grupo\n4. Materia\n5. Salir\n",
           "registro": "registro", "modifico": "modifico", "borro": "borro", "cuerpo_borro": "se le borro la nota llamada ",
           "cuerpo_borrado2" : " de la materia ", "cuerpo_resto" : "su nota en ", "cuerpo_resto2" :"con nombre de ",
           "cuerpo_resto3" : " fue de ", "cuerpo_resto4" : " y vale ", "cuerpo_resto5" : " % de la nota final",
           "asunto" : "se le ", "asunto2": " una nota",
           "emailSatisfactory": "Se ha enviado un correo al estudiante con la operacion realizada."}

    ing = {"mat": "Subject", "idi": "1 for Spanish, 2 for English", "id": "Id", "idePro": "Teacher identification",
           "numGrp": "Group Number: ", "ideNot": "Score Identification: ", "reporte": "Report Generated", "reportErr": "Error unexpected: Permission Denied",
           "ideEstu": "Student identification: ", "ideMate": "Matter identification: ", "menuMatt": "1. Search Matter\n2. Generate report\n3. Exit\n",
           "nom": "Name", "cre": "Credits", "gru": "Group", "reg": "Inserted", "mod": "Modified",
           "err": "Error", "eli": "Removed", "num": "Number", "pro": "Teacher",
           "usu": "User", "ide": "Identification", "cor": "Email", "con": "Password",
           "not": "Score", "por": "Percentage", "val": "Value", "ing Usu": "Enter your identification or email: ",
           "opnot": "1. Insert\n2. Modify\n3.Delete\n4. Search\n5. Exit\n", "noenc": "Not found",
           "ing Con": "Enter your password: ", "bie": "Welcome", "o": "or", "enc": "Found",
           "opc1": "1. Log in\n2. Close application\n3. Recover password\n",
           "opcAdmin": "1. Student\n2. Professor\n3. Administrator\n4. Matter\n5. Group\n6. Log Out\n",
           "opcProf": "1. Score\n2. Group\n3. Matter\n4. Log Out\n",
           "CASE": "1. Register\n2. Consult\n3. Modify\n4. Delete\n5. To list\n6. Go back", "busgrp": "1. Search group\n2. Exit\n",
           "CASEGru": "1. Register\n2. Consult\n3. Modify\n4. Delete\n5. List all\n6. List by subject\n7. Go back",
           "codi": "Code: ", "recu": "Password recovery", "nuecon": "New Password: ",
           "registro": "register", "modifico": "modify", "borro": "delete", "cuerpo_borro": "Was deleted your score called ",
           "cuerpo_borro2" : " from the signature ", "cuerpo_resto" : "Your note in ", "cuerpo_resto2" :"with name ",
           "cuerpo_resto3" : " was ", "cuerpo_resto4" : " and has ", "cuerpo_resto5" : " % from the final signature score",
           "asunto" : "it's had been ", "asunto2": " a score",
           "emailSatisfactory": "We have send an email with the operation made"}

    mensa = {}
